/*-----------------------------------------------------------------------------
    Name: flow
    Generated By: Shashank
    Date of generation: 09/22/2020 04:48:50
    Flow details:
    Build details: 4.3.0 (build# 103)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

void SentAuthCode()

{
    ns_start_transaction("SentAuthCode");
    ns_web_url ("SentAuthCode",
           "URL=https://api-test1.gamestop.com/adapter/v2/customers/SendAuthenticationCode?email=subratlegacy03@yopmail.com",
           //"URL=https://blue-mobileapi.gstop-preprod.com/v2/authorization/tokenV2",
           "METHOD=POST",
         //"HEADER=Authorization: AWS4-HMAC-SHA256 Credential=AKIAQJYD6VR3J35KXAIM/20200922/us-east-1/execute-api/aws4_request,  
         //"HEADER=X-Amz-Content-Sha256: 0ad78986eeec5b351daecc1ce17da3ac6798d1dd7e1d04cafeb73f56393aefd6",
		 //"HEADER=X-Amz-Date: 20200922T085405Z",
		 //"HEADER=Authorization: BASIC bmV0c3Rvcm06bmV0c3Rvcm0=",
           "HEADER=Cache-Control: no-cache",
           "HEADER=Content-Type: application/x-www-form-urlencoded",
           "HEADER=Content-Length: 239", 
           "HEADER=User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
           "HEADER=Accept: */*",
           "HEADER=Accept-Encoding: gzip, deflate, br",
           "HEADER=Connection: keep-alive",
           "HEADER=x-developer-key: {XDevloperKey_FP}",
           "HEADER=x-device: 51CF1F4D-37F7-4398-9124-0DE3648024B8",
           "HEADER=X-GS-Override: aa9Sul1eiYuPoamu",
           "HEADER=X-App-Version: 680",
           "HEADER=Authorization:JWTToken {AccessTokenSP}",
           "BODY=$CAVINCLUDE$=SentAuthCode.json",
    );
           ns_end_transaction("SentAuthCode", NS_AUTO_STATUS);
         ns_page_think_time(0);
}

