/*-----------------------------------------------------------------------------
    Name: ViewCart_Mobile
    Generated By: Shashank
    Date of generation: 09/24/2020 09:00:19
    Flow details:
    Build details: 4.3.0 (build# 103)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void ViewCart_Mobile()
{
return;
    ns_start_transaction("ViewCart_Mobile");
    ns_web_url ("ViewCart_Mobile",
           "URL=https://perf.gamestop.com/s/gamestop-us/cart/?target=gsnativeapp&cart=redesign&showSDD=true",
           // "URL=https://perf.gamestop.com/adapter/s/gamestop-us/cart/?target=gsnativeapp&cart=redesign&showSDD=true",
           "METHOD=GET",
           "HEADER=Authorization:Basic c3RvcmVmcm9udDpHaXZlTWU1MDBCdWNrcw==",
//           "HEADER=Connection:keep-alive",
//           "HEADER=Upgrade-Insecure-Requests:1",
//           "HEADER=User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36",
//           "HEADER=Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
//           "HEADER=Referer:https://www.gamestop.com/video-games/switch/accessories/controllers/products/nintendo-switch-joy-con-l-r-neon-red-neon-blue/10141870.html?rt=productDetailsRedesign&utm_expid=.h77-PyHtRYaskNpc14UbmA.1&utm_referrer=https%3A%2F%2Fwww.gamestop.com%2Fvideo-games%2Fswitch%2Faccessories",
//           "HEADER=Accept-Encoding:gzip, deflate, br",
//           "HEADER=Accept-Language:en-GB,en-US;q=0.9,en;q=0.8",
           //  "HEADER=X-GS-Override: aa9Sul1eiYuPoamu",
           "HEADER=Pragma:akamai-x-get-client-ip, akamai-x-cache-on, akamai-x-cache-remote-on, akamai-x-check-cacheable, akamai-x-get-cache-key, akamai-x-get-extracted-values, akamai-x-get-nonces, akamai-x-get-ssl-client-session-id, akamai-x-get-true-cache-key, akamai-x-serial-no, akamai-x-feo-trace, akamai-x-get-request-id",
           "COOKIE=__cfduid;dwac_a78eb5a11975e4c9cbc84f55ad;cqcid;sid;dwanonymous_420142ceefb9f0c103b3815e84e9fcef;__cq_dnt;dw_dnt;dwsid;bm_sz;ak_bmsc;RES_TRACKINGID;RES_SESSIONID;ResonanceSegment;_caid;_cavisit;_gcl_au;_mibhv;__cq_uuid;__cq_seg;spid;sp_ssid;_ga;_gid;_fbp;__gads;QuantumMetricUserID;QuantumMetricSessionID;_aeaid;aeatstartmessage;BVBRANDID;BVBRANDSID;QSI_HistorySession;_gat_UA-10897913-30;_gaexp;rt;RT;__cq_bc;_uetsid;_uetvid;mp_gamestop_mixpanel;stc118903;BVImplsfcc;QSI_S_SI_3wI8Q9U6pfO1aAZ;dwapupreq;bm_sv;_abck;ADRUM",
     
    );

 if (strcmp(ns_eval_string("{EmptyCartCheckSP}"),"Empty") == 0) 
         {
	         ns_end_transaction_as("ViewCart_Mobile", 0, "ViewCart_Mobile_Empty"); 
         	ns_exit_session();
         }
           
           ns_end_transaction("ViewCart_Mobile", NS_AUTO_STATUS);
         ns_page_think_time(0);

}
