/*-----------------------------------------------------------------------------
    Name: Cert_EnrollTibco
    Generated By: Shashank
    Date of generation: 09/24/2020 09:00:19
    Flow details:
    Build details: 4.3.0 (build# 103)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void Cert_EnrollTibco()
{

	
 char signature[512];
 char amzDate[128];
 char dateStamp[128];
 char body[2496+1];

 ns_advance_param("xmlbody");
 
 
 ns_advance_param("DateAWS");
//ns_save_string(ns_eval_string("{DateAWS}"),"Time_DP7");
strcpy(amzDate, ns_eval_string("{DateAWS}"));
  //strcpy(stime, ns_eval_string("{DateAWS}"));
 
	 printf("date1 = %s\n", amzDate);

 ns_advance_param("DateStamp");
//ns_save_string(ns_eval_string("{DateStamp}"),"Time_DP8");
strcpy(dateStamp, ns_eval_string("{DateStamp}"));
printf("date2 = %s\n", dateStamp);
 
 #if 0
 char *body=
"<soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:v1='http://schemas.gamestop.com/shared/commonschemas/v1.0' xmlns:v11='http://schemas.gamestop.com/marketing/loyaltylifecycle/loyaltymembershipservice/messagetypes/v1.0'>"
 "<soapenv:Header>"
    "<v1:MessageHeaders>"
     "<MachineName>USGVL9QNFSY1</MachineName>"
      "<KeyValuePairs>"
        "<KeyValuePair>"
          "<Key>channeltype</Key>"
          "<Value>PointOfSale</Value>"
        "</KeyValuePair>"
        "<KeyValuePair>"
          "<Key>storenumber</Key>"
          "<Value>480</Value>"
        "</KeyValuePair>"
      "</KeyValuePairs>"
      "<CultureInfo>"
        "<Locale>en-US</Locale>"
        "<TimeZone>CST</TimeZone>"
        "<CountryCode>US</CountryCode>"
      "</CultureInfo>"
    "</v1:MessageHeaders>"
  "</soapenv:Header>"
  "<soapenv:Body>"
    "<v11:EnrollCustomerForMembershipRequest>"
      "<v11:Customer>"
        "<Addresses>"
          "<Address>"
            "<AddressLine1>62451 Westport Pkwy</AddressLine1>"
            "<AddressLine2/>"
            "<AddressType>Home</AddressType>"
            "<City>Grapevine</City>"
            "<Country>US</Country>"
            "<FirstName>ECPProTestFirst</FirstName>"
            "<IsDefault>true</IsDefault>"
            "<LastName>ECPProTestLast</LastName>"
            "<PostalCode>76051</PostalCode>"
            "<StateOrProvince>TX</StateOrProvince>"
          "</Address>"
        "</Addresses>"
        "<EmailAddress>rishabhsharma@gmail.com</EmailAddress>"
        "<FirstName>Drew</FirstName>"
        "<Phones>"
          "<Phone>"
            "<HomePhoneNumber>5105887500</HomePhoneNumber>"
            "<PrimaryPhone>Home</PrimaryPhone>"
          "</Phone>"
        "</Phones>"
        "<LastName>Lindsay</LastName>"
        "<LoyaltyInfo>"
          "<IsLockedOut>false</IsLockedOut>"
          "<LoginTimeStamp>2019-03-21T14:56:32.0000000-06:00</LoginTimeStamp>"
          "<LoyaltyCardNumber>9818214980</LoyaltyCardNumber>"
          "<Tier>3876</Tier>"
          "<TierExpirationDate>2020-03-21T14:56:32.0000000-06:00</TierExpirationDate>"
          "<TierSignUpDate>2019-03-21T14:56:32.0000000-06:00</TierSignUpDate>"
        "</LoyaltyInfo>"
      "</v11:Customer>"
    "</v11:EnrollCustomerForMembershipRequest>"
  "</soapenv:Body>"
"</soapenv:Envelope>";
#endif 

 //ns_save_string("", "declare");

  char EmailValueAccountLinking[64];
   //  char signature= null;
	//ns_get_hmac_signature_ex("POST","https://apigateway.gstop-preprod.com/loyalty-service", buffer, "us-east-1", "AKIAJKFGGI6W4KNZCW4Q", "oFi1a9+SEzw1Ul9d7LvSb0xK6TqeTZQdwdUUoEXO", date1, date2, xyz);
char method[16+1]="POST";
char uri[512+1]="https://apigateway.gstop-preprod.com/loyalty-service"; 
char region[32+1]="us-east-1";
char key[32+1]="AKIAJKFGGI6W4KNZCW4Q";
char ksecret[64+1]="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";
char service[32+1]="execute-api";

//char str1[512+1], str2[512+1], str3[512+1], str4[512+1], str5[512+1];
char canonicalHeaders[1024+1], signedHeaders[512+1];
strcpy(canonicalHeaders, "host:apigateway.gstop-preprod.com\n");
strcat(canonicalHeaders, "soapaction:/Marketing/LoyaltyLifecycle/LoyaltyMembershipService/EnrollCustomerForMembership\n");
strcat(canonicalHeaders, "x-amz-content-sha256:beaead3198f7da1e70d03ab969765e0821b24fc913697e929e726aeaebf0eba3\n");
int len=strlen(canonicalHeaders);
sprintf(canonicalHeaders+len,"x-amz-date:%s\n",amzDate);
strcat(canonicalHeaders, "x-api-key:2FVM1ReQIe86rAbEPMcjT7NVT8r9pPWQfwx8OJEj\n");



//sprintf(canonicalHeaders, "%s", strcat(str1,strcat(str2,strcat(str3,strcat(str4,str5)))));

//fprintf(stderr,"Shree: ***********%s,len=%d\n", canonicalHeaders,strlen(canonicalHeaders));

sprintf(signedHeaders, "%s", "host;soapaction;x-amz-content-sha256;x-amz-date;x-api-key");
//fprintf(stderr,"Ayesha: ***********%s\n", signedHeaders);
strcpy(body,ns_eval_string("{xmlbody}"));



  ns_aws_signature(method, uri, canonicalHeaders, signedHeaders, body, region, service, key, ksecret, amzDate, dateStamp, signature);

	//ns_hmac_signature(method, url, buffer, region, key, ksecret, date1, date2, xyz, kservice);
//     sign=ns_eval_string("this is signature={signature}");
	fprintf(stderr, "\n\n**%s**\n\n",signature);
ns_save_string(signature,"skey");

//ns_save_string(date1,"awsDate");
//ns_save_string(date2,"awsDateStamp");

	//fprintf(stderr, "**DateAWS %d",date1);
	//fprintf(stderr, "**DateStamp %d",date2);

	
	


	//ns_save_string(ns_encode_url("2FVM1ReQIe86rAbEPMcjT7NVT8r9pPWQfwx8OJEj", 1024),"skey");

   // skey = ns_encode_url("2FVM1ReQIe86rAbEPMcjT7NVT8r9pPWQfwx8OJEj", 1024);
//strcpy(ns_encode_url("2FVM1ReQIe86rAbEPMcjT7NVT8r9pPWQfwx8OJEj", 1024),"{skey}");
 

    fprintf(stderr,"%s",ns_hmac("xyz",3,ksecret,strlen(ksecret),"SHA256",1));
    //return 0;

    ns_start_transaction("Cert_EnrollTibco");
    //fprintf(stderr,"\n***Rishabh**%s\n","{signature}");
    ns_web_url ("Cert_EnrollTibco",
         //  "URL=https://blue-mobileapi.gamestop.com/v2/customers/AccountLinking?email={Email_AL_FP}",
           "URL=https://apigateway.gstop-preprod.com/loyalty-service",
//          "URL=https://blue-mobileapi.gamestop.com/v2/customers/AccountLinking?email=AL_{CreateEmailRP}{CreateUQ}@bh.exacttarget.com",
          "METHOD=POST",
           "HEADER=Cache-Control: no-cache",
           "HEADER=X-Amz-Date: {DateAWS}",
            "HEADER=Authorization: AWS4-HMAC-SHA256 Credential=AKIAJKFGGI6W4KNZCW4Q/{DateStamp}/us-east-1/execute-api/aws4_request, SignedHeaders=host;soapaction;x-amz-content-sha256;x-amz-date;x-api-key, Signature={skey}",
           // "HEADER=Authorization: AWS4-HMAC-SHA256 Credential=AKIAJKFGGI6W4KNZCW4Q/20210702/us-east-1/execute-api/aws4_request, SignedHeaders=x-amz-date, Signature={skey}",
           //"HEADER=Authorization: AWS4-HMAC-SHA256 Credential=AKIAJKFGGI6W4KNZCW4Q/20210702/us-east-1/execute-api/aws4_request, SignedHeaders=host;soapaction;x-api-key, Signature={skey}",
           "HEADER=Accept:*/*",
          "HEADER=Accept-Encoding: gzip, deflate, br",
          "HEADER=X-Amz-Content-Sha256: beaead3198f7da1e70d03ab969765e0821b24fc913697e929e726aeaebf0eba3",
         "HEADER=Content-Type: application/xml",
         "HEADER=Content-Type: text/plain",
           "HEADER=Connection: keep-alive",
          "HEADER=x-api-key:2FVM1ReQIe86rAbEPMcjT7NVT8r9pPWQfwx8OJEj",
          "HEADER=SOAPAction:/Marketing/LoyaltyLifecycle/LoyaltyMembershipService/EnrollCustomerForMembership",
          "HEADER=correlation-id: AccountLinking_{CorrChar}{CorrID}",
           "HEADER=Cookie: _abck=ED73ADC355F7ECFAB19FCF53571F4C09~-1~YAAQdF06F2eZbzR6AQAAIfGUQgY02ly+BdbG2pXR78DheLs0/NQJ6OR/2lWpGgtTuw1aezSHVqRvGfFwIWpQjPn1i6FLTI6ilUX1UP2LJlbJkpE9GLRORXQ0IXSZ6CQiN+Ds8Mt4QSKK+8ooEIh9hi2htl3c2ElAmVTWHvWkT9GXuTS8IQiwAa1jmFNzRKE/oJO15Rz9mYxesgbhJkEzm2k1g6rGGOzo2Uzug0bPeLR7oKZxspCpjqmgWZ9PirITlTQNvpWBTvV1UC7Q+gIm3iA/Kn0ubYP0bTjIHAbQiade1kCaj6kWmQm8ubG4FOQq7srZvG/qkkSTmklUX12yZC8KBc7Gw2yjSGrx9utQMuQctHFEVKEJs49V+QyWd5p3ZswKBzWhjYwzhOJ1uXY=~-1~-1~1624525014",
             "BODY=$CAVINCLUDE$=CertEnrollTibco.xml",
     
    );



           ns_end_transaction("Cert_EnrollTibco", NS_AUTO_STATUS);
         ns_page_think_time(5);
//ns_save_data_ex("/home/cavisson/work/Game_Stop/GS/Mobile/GameStop_CreateAccount.txt",NS_APPEND_FILE,"%s",ns_eval_string("AL_{CreateEmailRP}{CreateUQ}@bh.exacttarget.com,GameStopPerf#01"));



         
snprintf(EmailValueAccountLinking, 64, "%s", ns_eval_string("{EmailAccountLinking}"));
ns_save_string(EmailValueAccountLinking,"DV_EmailValueAccountLinking");

}
